//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSPanel.h>

NS_ASSUME_NONNULL_BEGIN

NS_CLASS_AVAILABLE(10_12, NA)
@interface PIPPanel : NSPanel

- (void)mouseUp:(NSEvent*)arg1;
- (void)mouseDown:(NSEvent*)arg1;
- (void)performWindowDragWithEvent:(NSEvent*)arg1;
- (void)sendEvent:(NSEvent*)arg1;
- (id)initWithContentRect:(NSRect)arg1;

@end

NS_ASSUME_NONNULL_END
